Package.describe({
	name: "rista404:email-whitelist",
	summary: "Restrict registration to a whitelist of email addresses.",
	version: "0.4.0",
	git: "https://github.com/rista404/meteor-email-whitelist"
});

Package.onUse(function (api) {
	// Meteor releases below this version are not supported
	api.versionsFrom("1.2.0.1");

	// Core packages and 3rd party packages
	api.use("underscore", 'server');
	api.use("accounts-base", 'server');
	api.use("accounts-password", 'server');

	// The files of this package
	api.addFiles(["server/email-whitelist.js", "server/validation.js"], ["server"]);
	api.export(['emailWhitelisted']);
});

Package.onTest(function (api) {
	api.use("tinytest");
	api.use("rista404:email-whitelist");
	api.addFiles("tests/server/email-whitelist.js", ["server"]);
});

/* Generated by okgrow:package-kitchen */